// ─── VIDEOS ───────────────────────────────────────────────────────────────────
// Exact data from StreamAgent-v35.html lines 314-355
// Shape: { id, title, dur, views, plays, eng, color, age, status,
//          aspectRatio, resolution, fileSize, format, fps, audio,
//          uploadDate, uploadedBy, folder,
//          branding: { ... }, lp: { ... }, elements: [] }

export const VIDEOS = [
  {
    id: 1,
    resolution: '1920 × 1080',
    aspectRatio: '16:9',
    fileSize: '142 MB',
    format: 'MP4 / H.264',
    fps: '29.97 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 12, 2026',
    uploadedBy: 'Justin S.',
    title: 'Platform Overview',
    dur: '4:00',
    views: 8421,
    plays: 6203,
    eng: 78,
    color: '#4F6EF7',
    age: '2 days ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#4F6EF7', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'Watch This Free Video Training',
      body: 'Enter your info below and hit play to access the interactive training.',
      ctaText: 'Book a Free Call', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#4F6EF7', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Platform Overview | StreamAgent',
      seoDesc: 'Watch this free interactive video training.',
      published: false,
    },
    elements: [],
  },
  {
    id: 2,
    resolution: '1920 × 1080',
    aspectRatio: '16:9',
    fileSize: '98 MB',
    format: 'MP4 / H.264',
    fps: '29.97 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 10, 2026',
    uploadedBy: 'Justin S.',
    title: 'Lead Generation Guide',
    dur: '3:00',
    views: 3102,
    plays: 2891,
    eng: 91,
    color: '#1ED8A0',
    age: '5 days ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#1ED8A0', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'The Lead Gen Method Top Producers Use',
      body: 'Watch this free training and discover the exact system.',
      ctaText: 'Book a Strategy Call', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#1ED8A0', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Lead Generation Guide | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 3,
    resolution: '1080 × 1920',
    aspectRatio: '9:16',
    fileSize: '287 MB',
    format: 'MP4 / H.265',
    fps: '23.98 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 8, 2026',
    uploadedBy: 'Justin S.',
    title: 'Conversion Masterclass',
    dur: '3:20',
    views: 1847,
    plays: 1203,
    eng: 65,
    color: '#A855F7',
    age: '1 week ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#A855F7', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'native',
    },
    lp: {
      headline: 'Conversion Masterclass',
      body: 'Learn the exact framework top closers use to convert leads into clients.',
      ctaText: 'Get Instant Access', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#A855F7', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Conversion Masterclass | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 4,
    resolution: '1920 × 1080',
    aspectRatio: '16:9',
    fileSize: '76 MB',
    format: 'MP4 / H.264',
    fps: '30 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 5, 2026',
    uploadedBy: 'Justin S.',
    title: 'Brand Strategy',
    dur: '2:40',
    views: 5209,
    plays: 4102,
    eng: 82,
    color: '#F5A623',
    age: '2 weeks ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#F5A623', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'native',
    },
    lp: {
      headline: 'Build a Brand That Attracts Clients',
      body: 'Discover the brand strategy that separates top producers from everyone else.',
      ctaText: 'Watch Now', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#F5A623', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Brand Strategy | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 5,
    resolution: '1920 × 1080',
    aspectRatio: '16:9',
    fileSize: '54 MB',
    format: 'MP4 / H.264',
    fps: '29.97 fps',
    audio: 'AAC Mono',
    uploadDate: 'Mar 3, 2026',
    uploadedBy: 'Justin S.',
    title: 'Referral Strategy',
    dur: '2:20',
    views: 920,
    plays: 780,
    eng: 88,
    color: '#1ED8A0',
    age: '3 weeks ago',
    status: 'draft',
    folder: null,
    branding: {
      color: '#1ED8A0', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'native',
    },
    lp: {
      headline: 'The Referral Strategy That Runs on Autopilot',
      body: 'Get more referrals without asking for them.',
      ctaText: 'Learn How', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#1ED8A0', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Referral Strategy | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 6,
    resolution: '2560 × 1440',
    aspectRatio: '16:9',
    fileSize: '201 MB',
    format: 'MP4 / H.264',
    fps: '60 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Feb 28, 2026',
    uploadedBy: 'Justin S.',
    title: 'Digital Lead Mastery',
    dur: '2:30',
    views: 412,
    plays: 380,
    eng: 93,
    color: '#F06292',
    age: '1 month ago',
    status: 'draft',
    folder: null,
    branding: {
      color: '#F06292', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'Digital Lead Mastery',
      body: 'Master the digital strategies that fill your pipeline with qualified leads.',
      ctaText: 'Start Learning', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#F06292', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Digital Lead Mastery | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 7,
    resolution: '1080 × 1920',
    aspectRatio: '9:16',
    fileSize: '88 MB',
    format: 'MP4 / H.264',
    fps: '30 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 14, 2026',
    uploadedBy: 'Justin S.',
    title: '60-Second Listing Hook',
    dur: '1:00',
    views: 12840,
    plays: 11200,
    eng: 94,
    color: '#FF6B6B',
    age: '1 day ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#FF6B6B', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: '60-Second Listing Hook',
      body: 'Watch this quick vertical video to see the property.',
      ctaText: 'Schedule Showing', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#FF6B6B', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: '60-Second Listing Hook | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 8,
    resolution: '1080 × 1920',
    aspectRatio: '9:16',
    fileSize: '112 MB',
    format: 'MP4 / H.264',
    fps: '30 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 13, 2026',
    uploadedBy: 'Justin S.',
    title: 'Agent Intro Reel',
    dur: '0:45',
    views: 8920,
    plays: 7600,
    eng: 89,
    color: '#A855F7',
    age: '2 days ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#A855F7', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'Meet Your Agent',
      body: 'Quick intro — who I am and how I help.',
      ctaText: 'Book a Call', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#A855F7', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Agent Intro Reel | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 9,
    resolution: '1080 × 1920',
    aspectRatio: '9:16',
    fileSize: '95 MB',
    format: 'MP4 / H.264',
    fps: '30 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 12, 2026',
    uploadedBy: 'Justin S.',
    title: 'Market Update Short',
    dur: '1:30',
    views: 6340,
    plays: 5100,
    eng: 86,
    color: '#06B6D4',
    age: '3 days ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#06B6D4', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'Market Update',
      body: 'Quick weekly market snapshot for your area.',
      ctaText: 'Get Full Report', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#06B6D4', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Market Update Short | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
  {
    id: 10,
    resolution: '1080 × 1080',
    aspectRatio: '1:1',
    fileSize: '76 MB',
    format: 'MP4 / H.264',
    fps: '30 fps',
    audio: 'AAC Stereo (L R)',
    uploadDate: 'Mar 11, 2026',
    uploadedBy: 'Justin S.',
    title: 'Testimonial Spotlight',
    dur: '2:00',
    views: 4210,
    plays: 3800,
    eng: 91,
    color: '#F5A623',
    age: '4 days ago',
    status: 'published',
    folder: null,
    branding: {
      color: '#F5A623', font: 'Outfit', logoText: 'StreamAgent', logoUrl: '',
      thumbnailUrl: '', autoplay: false, controls: true, badge: true,
      captions: false, chapters: false, playerMode: 'stream',
    },
    lp: {
      headline: 'Hear From Our Clients',
      body: 'Real results from real clients.',
      ctaText: 'Start Your Journey', ctaUrl: '',
      bg: '#0F172A', tc: '#EEF2FF', brand: '#F5A623', font: 'Outfit',
      logoText: 'StreamAgent', logoUrl: '',
      showLogo: true, showHero: false, showHeadline: true, showVideo: true,
      showBody: true, showCTA: true, showComments: false, showPowered: true,
      seoTitle: 'Testimonial Spotlight | StreamAgent', seoDesc: '',
      published: false,
    },
    elements: [],
  },
]

// ─── FOLDERS ──────────────────────────────────────────────────────────────────
export const FOLDERS = [
  { id: 'Lead Videos',  color: '#4F6EF7' },
  { id: 'Sales Videos', color: '#F5A623' },
  { id: 'Lead Gen',     color: '#1ED8A0' },
]

// ─── HEATMAP ──────────────────────────────────────────────────────────────────
// 40-point watch-depth curve — deterministic version of the HTML's Math.random()
export const HEATMAP = [
  100, 97, 94, 92, 90, 87, 85, 83, 111, 79,
  77, 75, 73, 71, 69, 67, 65, 63, 61, 59,
  57, 55, 68, 51, 49, 47, 45, 43, 41, 39,
  37, 35, 33, 31, 29, 27, 25, 23, 21, 19,
]

// ─── INIT ROUTES (Route Builder canvas nodes) ─────────────────────────────────
export const INIT_ROUTES = [
  {
    id: 'root',
    title: 'Platform Overview',
    x: 300, y: 180,
    color: '#4F6EF7',
    duration: 240,
    isRoot: true,
    choicePoints: [
      {
        id: 'cp1',
        triggerAt: 60,
        question: "What's your biggest challenge?",
        subtitle: 'Choose your path',
        choices: [
          { id: 'c1a', label: 'More leads',          icon: '🎯', color: '#4F6EF7', targetId: 'lead-gen'   },
          { id: 'c1b', label: 'Better conversions',  icon: '💰', color: '#1ED8A0', targetId: 'conversion'  },
          { id: 'c1c', label: 'Build my brand',      icon: '🚀', color: '#F5A623', targetId: 'brand'       },
        ],
      },
    ],
    ctaPoints: [
      { id: 'cta1', triggerAt: 30, type: 'email-capture', headline: 'Get the free playbook', sub: 'The exact framework top producers use', cta: 'Send Me the Playbook', color: '#4F6EF7' },
    ],
  },
  {
    id: 'lead-gen',
    title: 'Lead Generation Guide',
    x: 60, y: 440,
    color: '#4F6EF7',
    duration: 180,
    choicePoints: [],
    ctaPoints: [
      { id: 'cta2', triggerAt: 45, type: 'booking', headline: 'Book a strategy call', sub: '30 min. No pitch.', cta: 'Reserve My Spot', color: '#4F6EF7' },
    ],
  },
  {
    id: 'conversion',
    title: 'Conversion Masterclass',
    x: 340, y: 440,
    color: '#1ED8A0',
    duration: 200,
    choicePoints: [],
    ctaPoints: [
      { id: 'cta3', triggerAt: 40, type: 'download', headline: 'Download scripts', sub: 'Word-for-word closing scripts', cta: 'Download Free', color: '#1ED8A0' },
    ],
  },
  { id: 'brand',    title: 'Brand Strategy',     x: 620, y: 440, color: '#F5A623', duration: 160, choicePoints: [], ctaPoints: [] },
  { id: 'referral', title: 'Referral Strategy',  x: 60,  y: 680, color: '#1ED8A0', duration: 140, choicePoints: [], ctaPoints: [] },
  { id: 'digital',  title: 'Digital Lead Mastery', x: 340, y: 680, color: '#F06292', duration: 150, choicePoints: [], ctaPoints: [] },
]

// ─── ELEMENT TYPES (25 types across 4 categories) ────────────────────────────
export const EL_TYPES = {
  'cta-email':      { cat: 'capture', label: 'Lead Capture',       icon: '✉️',  color: '#4F6EF7', desc: 'Collect emails mid-video',                dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, headline: 'Get the free playbook', sub: "Drop your email and we'll send it instantly", buttonText: 'Send Me the Playbook', buttonColor: '#4F6EF7', showInput: true } },
  'cta-button':     { cat: 'overlay', label: 'Click Button',        icon: '👆',  color: '#1ED8A0', desc: 'Link to any URL',                          dw: 190, dh: 40,  defs: { text: 'Learn More →', buttonColor: '#1ED8A0', url: '', style: 'filled' } },
  'cta-booking':    { cat: 'capture', label: 'Book a Call',          icon: '📅',  color: '#A855F7', desc: 'Calendar booking',                         dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, headline: 'Book a free strategy call', sub: '30 minutes. No pitch.', buttonText: 'Reserve My Spot', buttonColor: '#A855F7' } },
  'cta-download':   { cat: 'capture', label: 'Download',             icon: '⬇️',  color: '#F5A623', desc: 'Offer a file download',                    dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, headline: 'Download the free playbook', buttonText: 'Download Now', buttonColor: '#F5A623' } },
  'overlay-text':   { cat: 'overlay', label: 'Text Overlay',         icon: 'T',   color: '#EEF2FF', desc: 'Animated text',                            dw: 310, dh: 58,  defs: { text: 'Your compelling headline here', fontSize: 20, color: '#EEF2FF', background: 'rgba(0,0,0,0.5)', align: 'center' } },
  'overlay-countdown': { cat: 'overlay', label: 'Countdown Timer',   icon: '⏱',  color: '#F5A623', desc: 'Urgency countdown',                        dw: 195, dh: 78,  defs: { label: 'Offer ends in', minutes: 10, seconds: 0, color: '#F5A623' } },
  'overlay-chapter':{ cat: 'overlay', label: 'Chapter Title',        icon: '📖',  color: '#1ED8A0', desc: 'Section title card',                       dw: 340, dh: 68,  defs: { chapter: 'Chapter 1', title: 'Introduction', color: '#1ED8A0' } },
  'share-social':   { cat: 'overlay', label: 'Social Share',         icon: '🔗',  color: '#F06292', desc: 'Share buttons',                            dw: 230, dh: 58,  defs: { label: 'Share this video', platforms: ['twitter', 'linkedin', 'facebook'], color: '#F06292', layout: 'horizontal' } },
  'survey-poll':    { cat: 'survey',  label: 'Poll / Survey',        icon: '📊',  color: '#A855F7', desc: 'Single question poll',                     dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, question: 'What matters most to you?', options: ['More leads', 'Better conversions', 'Build my brand', 'Save time'], multiSelect: false, buttonText: 'Submit Answer', buttonColor: '#A855F7', showResults: true } },
  'survey-rating':  { cat: 'survey',  label: 'Star Rating',          icon: '⭐',  color: '#F5A623', desc: '1-5 star rating widget',                   dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, question: 'How valuable was this information?', stars: 5, buttonText: 'Submit Rating', buttonColor: '#F5A623', showAverage: true } },
  'survey-nps':     { cat: 'survey',  label: 'NPS Score',            icon: '📈',  color: '#06B6D4', desc: 'Net Promoter Score 0-10',                  dw: 840, dh: 472, defs: { collectName: true, collectPhone: true, question: 'How likely are you to recommend us?', lowLabel: 'Not likely', highLabel: 'Very likely', buttonColor: '#06B6D4', buttonText: 'Submit' } },
  'funnel-urgency': { cat: 'capture', label: 'Lead Gate + Urgency',  icon: '🔥',  color: '#FF6B6B', desc: 'Full-screen capture with limited spots badge', dw: 840, dh: 472, defs: { progressPct: 50, progressLabel: '50% Completed', headline: 'Want to Continue Watching?', subheadline: 'Enter Your Details Below', collectName: true, collectEmail: true, collectPhone: true, phoneRequired: false, buttonText: 'Continue Watching →', buttonColor: '#FF6B6B', urgencyText: 'Only 3 spots left at this price — claim yours now', urgencyType: 'spots', spotsLeft: 3, showCountdown: false, countdownMins: 10, blurVideo: true, allowSkip: false, skipText: "No thanks, I don't want access", successMessage: "You're in! Continuing your video…" } },
  'sticky-bar':     { cat: 'overlay', label: 'Sticky CTA Bar',       icon: '📌',  color: '#FF6B6B', desc: 'Persistent top/bottom bar',                dw: 840, dh: 48,  defs: { text: '🔥 Limited spots available — Book your free strategy call', buttonText: 'Book Now →', buttonColor: '#FF6B6B', url: '', position: 'bottom', barBg: 'rgba(7,9,15,0.92)' } },
  'annotation-link':{ cat: 'overlay', label: 'Annotation Card',      icon: '🔗',  color: '#A855F7', desc: 'Corner pop-in link card',                  dw: 220, dh: 72,  defs: { title: 'Watch Next', sub: 'Advanced Strategy Session', url: '', thumbnailEmoji: '🎬', color: '#A855F7', position: 'bottom-right' } },
  'image-clickable':{ cat: 'overlay', label: 'Clickable Image',      icon: '🖼️', color: '#06B6D4', desc: 'Image overlay with link',                   dw: 200, dh: 150, defs: { imageUrl: '', imageName: '', url: 'https://', openNewTab: true, borderRadius: 8, opacity: 1, objectFit: 'contain', altText: '' } },
  // Mobile-Only
  'mob-call':       { cat: 'mobile',  label: 'Tap to Call',          icon: '📞',  color: '#1ED8A0', desc: 'One-tap phone call button',                dw: 240, dh: 52,  defs: { phone: '', label: 'Call Now', subtitle: 'Tap to connect instantly', style: 'pill', bgColor: '#1ED8A0' } },
  'mob-sms':        { cat: 'mobile',  label: 'Tap to Text',          icon: '💬',  color: '#4F6EF7', desc: 'Pre-filled SMS message',                   dw: 240, dh: 52,  defs: { phone: '', message: "Hi! I just watched your video and I'm interested.", label: 'Text Us', bgColor: '#4F6EF7' } },
  'mob-vcard':      { cat: 'mobile',  label: 'Save Contact',         icon: '👤',  color: '#A855F7', desc: 'Download vCard to phone contacts',          dw: 240, dh: 60,  defs: { name: '', phone: '', email: '', company: '', title: '', label: 'Save My Contact', bgColor: '#A855F7' } },
  'mob-calendar':   { cat: 'mobile',  label: 'Add to Calendar',      icon: '📅',  color: '#F5A623', desc: 'Add event to phone calendar',               dw: 240, dh: 60,  defs: { eventTitle: '', eventDate: '', eventTime: '', eventLocation: '', eventDuration: 60, label: 'Add to Calendar', bgColor: '#F5A623' } },
  'mob-swipe':      { cat: 'mobile',  label: 'Swipe Up CTA',         icon: '👆',  color: '#FF6B6B', desc: 'Instagram-style swipe up prompt',           dw: 240, dh: 90,  defs: { label: 'Swipe Up to Learn More', url: '', bgColor: '#FF6B6B', arrowAnim: true } },
  'mob-share':      { cat: 'mobile',  label: 'Share via Text',       icon: '📤',  color: '#06B6D4', desc: 'Pre-filled SMS share link',                 dw: 240, dh: 52,  defs: { message: 'Check out this video:', label: 'Share with a Friend', bgColor: '#06B6D4' } },
  'mob-directions': { cat: 'mobile',  label: 'Get Directions',       icon: '📍',  color: '#FF6B35', desc: 'Opens Maps to an address',                  dw: 240, dh: 60,  defs: { address: '', label: 'Get Directions', subtitle: 'Open in Maps', bgColor: '#FF6B35' } },
  'mob-screenshot': { cat: 'mobile',  label: 'Screenshot CTA',       icon: '📸',  color: '#F06292', desc: 'Styled card designed to be screenshotted',  dw: 240, dh: 160, defs: { headline: 'Save This Info', line1: '', line2: '', line3: '', phone: '', bgColor: '#0F172A', accentColor: '#F06292' } },
  'mob-shake':      { cat: 'mobile',  label: 'Shake to Reveal',      icon: '🫨',  color: '#FFD700', desc: 'Shake phone to reveal hidden offer',         dw: 240, dh: 100, defs: { hiddenText: 'Use code SAVE20 for 20% off!', promptText: 'Shake your phone for a surprise!', bgColor: '#FFD700', revealBg: '#1ED8A0' } },
}

// ─── ELEMENT CATEGORIES ───────────────────────────────────────────────────────
export const EL_CATS = [
  { id: 'capture', label: 'Lead Capture',    icon: '⚡', color: '#4F6EF7' },
  { id: 'overlay', label: 'Overlays',        icon: '🎨', color: '#F5A623' },
  { id: 'survey',  label: 'Polls',           icon: '📊', color: '#A855F7' },
  { id: 'mobile',  label: 'Mobile Exclusive',icon: '📱', color: '#1ED8A0' },
]

// ─── LANDING PAGES (Route-level, separate from video LP) ─────────────────────
export const LANDING_PAGES = [
  { id: 1, name: 'Lead Capture Page',  url: 'streamagent.com/p/lead-capture',     status: 'published', routeId: null,      views: 1842, color: '#4F6EF7' },
  { id: 2, name: 'Sales Presentation', url: 'streamagent.com/p/sales-presentation', status: 'published', routeId: 'route-2', views: 934,  color: '#1ED8A0' },
  { id: 3, name: 'Event Follow-Up',    url: 'streamagent.com/p/event-follow-up',   status: 'draft',     routeId: null,      views: 0,    color: '#F5A623' },
  { id: 4, name: 'Referral Page',      url: 'streamagent.com/p/referral',          status: 'published', routeId: null,      views: 421,  color: '#A855F7' },
]

// ─── LEADS ────────────────────────────────────────────────────────────────────
export const LEADS = [
  { id: 1,  name: 'Sarah Mitchell',  email: 'sarah.m@gmail.com',      phone: '(310) 555-0192', video: 'Platform Overview',        branch: 'Lead Gen',   watchPct: 91, status: 'Qualified', score: 95, date: '2 hours ago',  source: 'Facebook Ad',  campaign: 'Realtor Lead Gen',    notes: 'Called twice. Very interested in upgrading.', tags: ['hot','prospect'],   followUp: '2026-03-21', rewatched: false },
  { id: 2,  name: 'James Kowalski',  email: 'jkowalski@outlook.com',  phone: '(424) 555-0847', video: 'Lead Generation Guide',    branch: 'Conversion', watchPct: 78, status: 'Contacted', score: 74, date: '5 hours ago',  source: 'Email',        campaign: 'Follow-Up Sequence', notes: '',                                            tags: ['prospect'],         followUp: '2026-03-20', rewatched: false },
  { id: 3,  name: 'Priya Nair',      email: 'priya.nair@yahoo.com',   phone: '',               video: 'Agent Intro Reel',         branch: 'Brand',      watchPct: 55, status: 'New',       score: 52, date: '1 day ago',    source: 'Organic',      campaign: '',                    notes: '',                                            tags: [],                   followUp: null,         rewatched: true  },
  { id: 4,  name: 'Marcus Bell',     email: 'mbell@example.com',      phone: '(213) 555-3312', video: 'Conversion Masterclass',   branch: 'Lead Gen',   watchPct: 100,status: 'Closed',    score: 100,date: '2 days ago',   source: 'LinkedIn Ad',  campaign: 'B2B Outreach',        notes: 'Converted to annual plan. Referral opportunity.', tags: ['closed','referral'], followUp: null,         rewatched: false },
  { id: 5,  name: 'Angela Torres',   email: 'angietorres@gmail.com',  phone: '(818) 555-7741', video: 'Brand Strategy',           branch: 'Lead Gen',   watchPct: 44, status: 'New',       score: 38, date: '3 days ago',   source: 'Organic',      campaign: '',                    notes: '',                                            tags: [],                   followUp: null,         rewatched: false },
  { id: 6,  name: 'Derek Huang',     email: 'dhuang@gmail.com',       phone: '(310) 555-9283', video: 'Agent Intro Reel',         branch: 'Brand',      watchPct: 88, status: 'Contacted', score: 81, date: '3 days ago',   source: 'Instagram Ad', campaign: 'Brand Awareness',     notes: 'Evaluating options, ready to commit next quarter.', tags: ['prospect','warm'],  followUp: null,         rewatched: true  },
  { id: 7,  name: 'Nicole Reeves',   email: 'nreeves@hotmail.com',    phone: '(626) 555-0044', video: 'Lead Generation Guide',    branch: 'Conversion', watchPct: 62, status: 'New',       score: 57, date: '4 days ago',   source: 'Email',        campaign: 'Newsletter',          notes: '',                                            tags: [],                   followUp: null,         rewatched: false },
  { id: 8,  name: 'Tony Vasquez',    email: 'tvasquez@icloud.com',    phone: '(323) 555-8812', video: 'Referral Strategy',        branch: 'Lead Gen',   watchPct: 97, status: 'Qualified', score: 92, date: '5 days ago',   source: 'Facebook Ad',  campaign: 'Retargeting',         notes: 'Ready to commit within 60 days.',             tags: ['hot','prospect'],   followUp: '2026-03-25', rewatched: false },
  { id: 9,  name: 'Karen Powell',    email: 'kpowell@gmail.com',      phone: '(714) 555-6621', video: '60-Second Listing Hook',   branch: 'Lead Gen',   watchPct: 83, status: 'Qualified', score: 88, date: '6 days ago',   source: 'TikTok Ad',    campaign: 'Viral Hook Series',   notes: '',                                            tags: ['prospect'],         followUp: '2026-03-26', rewatched: false },
  { id: 10, name: 'Brian Castillo',  email: 'bcastillo@work.com',     phone: '',               video: 'Market Update Short',      branch: 'Brand',      watchPct: 32, status: 'New',       score: 22, date: '1 week ago',   source: 'Organic',      campaign: '',                    notes: '',                                            tags: [],                   followUp: null,         rewatched: false },
]

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const NOTIFICATIONS = [
  { id: 1, icon: '⚡', color: '#1ED8A0', title: 'New lead captured',        desc: 'Sarah M. submitted email on Platform Overview',          time: '2 min ago',  unread: true  },
  { id: 2, icon: '🎯', color: '#4F6EF7', title: 'Choice Point selected',   desc: 'James R. chose "More Leads" on Lead Gen Guide',          time: '18 min ago', unread: true  },
  { id: 3, icon: '🔥', color: '#FF6B6B', title: 'Video hit 1,000 plays',   desc: '60-Second Listing Hook reached a milestone',             time: '1 hour ago', unread: true  },
  { id: 4, icon: '📊', color: '#A855F7', title: 'Weekly report ready',     desc: 'Your analytics summary for Mar 14–21 is available',     time: '3 hours ago',unread: false },
  { id: 5, icon: '✅', color: '#1ED8A0', title: 'HubSpot sync complete',   desc: '12 new leads pushed to your CRM',                       time: '5 hours ago',unread: false },
  { id: 6, icon: '⚡', color: '#1ED8A0', title: 'New lead captured',        desc: 'David K. submitted email on Conversion Masterclass',     time: 'Yesterday',  unread: false },
]

// ─── BUILDER COLORS ───────────────────────────────────────────────────────────
export const BUILDER_COLORS = ['#4F6EF7','#1ED8A0','#F5A623','#F06292','#A855F7','#FF6B6B','#06B6D4','#E879F9']

// ─── HELPERS ──────────────────────────────────────────────────────────────────
export const fmt    = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`
export const mkId   = ()  => Math.random().toString(36).slice(2, 8)
export const clamp  = (v, a, b) => Math.max(a, Math.min(b, v))

// ─── ALIASES for old component files (prev project used these names) ──────────
// Remove these once all components are rebuilt from the HTML
export const MOCK_VIDEOS  = VIDEOS
export const MOCK_LEADS   = LEADS
export const MOCK_ROUTES  = INIT_ROUTES

export const STATUS_COLORS = {
  New:       { color: '#7B87A0', bg: 'rgba(123,135,160,0.1)' },
  Contacted: { color: '#4F6EF7', bg: 'rgba(79,110,247,0.1)'  },
  Qualified: { color: '#1ED8A0', bg: 'rgba(30,216,160,0.1)'  },
  Closed:    { color: '#A855F7', bg: 'rgba(168,85,247,0.1)'  },
  Lost:      { color: '#FF6B6B', bg: 'rgba(255,107,107,0.1)' },
}

export const PLAN_FEATURES = {
  core: {
    name: 'Core', price: 49,
    leads: 2500, videos: 25, routes: 10,
    features: ['Interactive elements', 'Landing pages', 'Route builder', 'Basic analytics', 'Email integrations'],
  },
  pro: {
    name: 'Pro', price: 99,
    leads: 10000, videos: 100, routes: 50,
    features: ['Everything in Core', 'Advanced analytics', 'CRM integrations', 'Custom branding', 'Priority support'],
  },
  agency: {
    name: 'Agency', price: 249,
    leads: -1, videos: -1, routes: -1,
    features: ['Everything in Pro', 'Unlimited everything', 'White label', 'Team seats', 'Dedicated support'],
  },
}